title: masenf.com
subtitle: programmer, father, musician
description: >- # this means to ignore newlines until "baseurl:"
  Making sense of the world in the best way I know how.
author: Masen Furer
email: mf@0x26.net
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
facebook_url: https://www.facebook.com/masenf
github_url: https://github.com/masenf
googleplus_url:
instagram_url: https://www.instagram.com/mjf289/
linkedin_url: https://www.linkedin.com/in/masen-furer-445b05132/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/masenf

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
#theme: jekyll-theme-prologue
# GH-PAGES support
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
plugins:
  - jekyll-redirect-from
